#define WRITEBYTE(WORD,BYTESTARTBIT,BYTE) WORD=((WORD&~(255<<BYTESTARTBIT))|(BYTE<<BYTESTARTBIT))


#define READBIT(WORD,BIT) ((WORD>>BIT)&1)


#define WRITEBIT(WORD,BITPOS,BIT) WORD=((WORD&~(1<<BITPOS))|(BIT<<BITPOS))


#define SETBIT(WORD,BITPOS) WORD|=1<<BITPOS

#define CLRBIT(WORD,BITPOS) WORD&=~(1<<BITPOS)

#define CPLBIT(WORD,BITPOS) WORD^=1<<BITPOS


#define READWRITEBIT(WORD,DBIT,SBIT) WORD=(((WORD&~(1<<DBIT))|((WORD>>SBIT)&1)<<DBIT))




#define READNIBBLE(WORD,NIBBLESTARTBIT)((WORD>>NIBBLESTARTBIT)&15)


#define WRITENIBBLE(WORD,NIBBLESTARTBIT,NIBBLE) WORD=((WORD&~(15<<NIBBLESTARTBIT))|(NIBBLE<<NIBBLESTARTBIT))

#define SSETBIT(WORD,BITPOS) WORD=(1<<BITPOS)
#define SCLRBIT(WORD,BITPOS) WORD=(1<<BITPOS)



